export const Enum={
    HISTORIAACADEMICA: 'historiaAcademica',
    HISTORIAACADEMICAESPECIAL: 'historiaAcademicaEspecial',
    CURSO:'curso',
    L1:'l1',
    L2:'l2',
    L3:'l3',
    FALLAS:'fallas',
    OBSERVACION: 'observacion',
    PRIVATEROUTE: '/private/dashboard/',
    PANELNOTESROUTE: '../panel-notes/',
    PANELNOTESROUTEPRESCHOOL: '../panel-notes-preschool/',
    REPORTLUGARES: '../report-lugares/',
    REPORTFINAL: '../reportfinal/',
    REPORTSABANAPRIMARIA: '../report-sabana/',
    PANELROUTE:'../panel/',
    PRESCHOOLROUTE:'../panel-preschool/',
    REPORTROUTE:'../report',
    RELATIVEPATH: '/private/dashboard/',
    REPORTSECUNDARIA: '../report-secondary/',
    REPORTSABANASECUNDARIA: '../report-sabana-s/',
    REPORTPRESCHOOL: '../report-preschool/',
    REPORTPRESCHOOLPRINT: '../report-preschool-print/'
}